version: "3.4"
services:
  node-app:     #container 1
    container_name: express-node-app
    ports:
      ["4000:4000"]
    env_file:
      - ./.env
  mongo:        #container 2
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:             # these volum to store data in hard drive in in /data/db directory inside mongo container
  mongo-db: